Separate test workflow for Ruby 2.2.10
Ruby 2.2.10 cannot be installed on the latest Ubuntu but the Ubuntu 20.04.

Reference: GitHub / ruby / setup-ruby / Bundler install appears broken
           on Ruby 2.2 / the summary comment by eregon [1]

Error output:

  Installing Bundler
    Bundler 2 requires Ruby 2.3+, using Bundler 1 on Ruby <= 2.2
    /opt/hostedtoolcache/Ruby/2.2.10/x64/bin/gem install bundler -v ~> 1.0
    ERROR:  While executing gem ... (RuntimeError)
        Marshal.load reentered at marshal_load
    Took   0.28 seconds

[1] https://github.com/ruby/setup-ruby/issues/496#issuecomment-1625000309